AccountingTask/Controllers/ConsumptionController.cs
using AccountingTask.Areas.Identity.Data;
using AccountingTask.Data;
using AccountingTask.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AccountingTask.Controllers
{
    public class ConsumptionController : Controller
    {
        private ApplicationContext _db;
        private UserManager<ApplicationUser> _userManager;
        public ConsumptionController(ApplicationContext db, UserManager<ApplicationUser> userManager)
		{
            _db = db;
            _userManager = userManager;
		}
		[HttpPost]
        public IActionResult Index(double ConsuptionSum, string ConsuptionText)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Consumption cons = new Consumption(ConsuptionSum, ConsuptionText, userId);
            _db.Consumptions.Add(cons);
            _db.SaveChanges();
            return RedirectToAction("Index","Home");
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

AccountingTask/Controllers/HomeController.cs
using AccountingTask.Areas.Identity.Data;
using AccountingTask.Data;
using AccountingTask.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace AccountingTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationContext _db;
        private UserManager<ApplicationUser> _userManager;
        public HomeController(ILogger<HomeController> logger, ApplicationContext db, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var id = _userManager.GetUserId(User);
                var user = _db.Users.Include(u => u.Consumptions).FirstOrDefault(u => u.Id == id);
                return View(user.Consumptions);
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AccountingTask/Views/Home/Index.cshtml
@model IEnumerable<Consumption>
@{
	ViewData["Title"] = "Home Page";
	var consumprionData = Model;
}

<div class="text-center">
	@if (User.Identity.IsAuthenticated)
	{
		<h1 class="display-4">Добро пожаловать @User.Identity.Name</h1>
		<a asp-controller="Consumption" asp-action="Index">Добавить трату</a>
		@if (consumprionData != null)
		{
			double sum = 0;
			@foreach (var consumption in consumprionData)
			{
				sum += consumption.ConsumptionSum;
				<h1 class="display-6">Трата:@consumption.ConsumptionText</h1>
				<h1 class="display-6">Цена:@consumption.ConsumptionSum</h1>
				<hr />
			}
			<h1 class="display-3">Всего к оплате:@sum</h1>
		}
	}
	else
	{
		<h1 class="display-4">Авторизуйтесь чтобы увидеть учет расходов</h1>
	}
</div>